GET http://localhost:3001/api/persons/613b60479dd39bcd897fb705


###

GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/6139aa36ef1336ad3d7e07c9

###

POST http://localhost:3001/api/persons/
content-type: application/json

{ 
      "number": "225-44444",
      "name": "Pudel"
      
    }

###

    POST https://morning-thicket-16795.herokuapp.com/api/persons

###

PUT http://localhost:3001/api/persons/613b60479dd39bcd897fb705



